name: agrosmart-middleware
services:
- name: agrosmart-web
  environment_slug: java-17
  source_dir: /
  github:
    repo: JeysonhT/Spring_Agrosmart_Middleware
    branch: main
    deploy_on_push: true
  build_command: mvn clean package -DskipTests
  run_command: java -jar target/*.jar --server.port=$PORT
  http_port: 8080
  instance_size_slug: basic-xxs
  instance_count: 1
  routes:
  - path: /